//
//  JournalProtocols.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

// MARK: Wireframe -
protocol JournalWireframeProtocol: class {

}
// MARK: Presenter -
@objc protocol JournalPresenterProtocol: class {
    func updateView()
    func journalFetched(dolgs: String, percent: String, score: String)
    @objc func showByDate()
    @objc func showBySubject()
    @objc func showMore()
}

// MARK: Interactor -
protocol JournalInteractorProtocol: class {
  func fetchJournal()
  var presenter: JournalPresenterProtocol? { get set }
}

// MARK: View -
protocol JournalViewProtocol: class {
    func setNeedsShowByDate()
    func setNeedsShowBySubject()
    func setNeedsShowMore()
    var presenter: JournalPresenterProtocol? { get set }
    func fillView(dolgs: String, percent: String, score: String)
    func show(vc: UIViewController)
}
