//
//  JournalProtocols.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol JournalWireframeProtocol: class {

}
// MARK: Presenter -
protocol JournalPresenterProtocol: class {
    func updateView()
    func journalFetched(dolgs: String, percent: String, score: String)
}

// MARK: Interactor -
protocol JournalInteractorProtocol: class {
  func fetchJournal()
  var presenter: JournalPresenterProtocol? { get set }
}

// MARK: View -
protocol JournalViewProtocol: class {

  var presenter: JournalPresenterProtocol? { get set }
  func setupView(dolgs: String, percent: String, score: String)
}
