//
//  JournalViewController.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class JournalViewController: UIViewController, JournalViewProtocol {

	var presenter: JournalPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
