//
//  ScheduleProtocols.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol ScheduleWireframeProtocol: class {

}
// MARK: Presenter -
protocol SchedulePresenterProtocol: class {
    func updateView()
    func teachersFetched(data: JSONDecoding.GetTeachersApi)
    func scheduleByGroupsFetched(data: JSONDecoding.GetGroupsApi)
    func studentScheduleFetched(data: JSONDecoding.StudentScheduleApi)
}

// MARK: Interactor -
protocol ScheduleInteractorProtocol: class {
    func fetchTeachers()
    func fetchScheduleByGroups()
    func fetchStudentSchedule()
  var presenter: SchedulePresenterProtocol? { get set }
}

// MARK: View -
protocol ScheduleViewProtocol: class {
    func showNewTeacherRows(source: JSONDecoding.GetTeachersApi)
    func showNewScheduleByGroupsRows(source: JSONDecoding.GetGroupsApi)
    func showNewStudentScheduleRows(source: JSONDecoding.StudentScheduleApi)
  var presenter: SchedulePresenterProtocol? { get set }
}
