//
//  ScheduleInteractor.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Alamofire

class ScheduleInteractor: ScheduleInteractorProtocol {
    weak var presenter: SchedulePresenterProtocol?
    func fetchTeachers() {
        let params: Parameters = [
            "app_key": Constants.AppKey
            ]
        Alamofire.request(Constants.TeachersURL, method: .get, parameters: params).responseJSON { (response) in
            let result = response.data
            do {
                let res = try JSONDecoder().decode(JSONDecoding.GetTeachersApi.self, from: result!)
                self.presenter?.teachersFetched(data: res)
                /*self.teachers = res.teachers
                self.teachersLoaded = true
                if self.groupsLoaded && self.teachersLoaded && self.myLoaded {
                    stopLoader()
                }
                for teach in res.teachers {
                    let index = teach.firstname.index(teach.lastname.startIndex, offsetBy: 0)
                    self.indexes.append(String(teach.lastname[index]))
                }
                DispatchQueue.main.async {
                    UIView.animate(withDuration: 1, animations: {
                        self.refreshButton.alpha = 0
                    })
                    self.tableView1.reloadData()
                }*/
            } catch {
                print(error)
            }
        }
    }
    func fetchScheduleByGroups() {
        let params: Parameters = [
            "app_key": Constants.AppKey
            ]
        Alamofire.request(Constants.GroupsURL, method: .get, parameters: params).responseJSON { (response) in
            let result = response.data
            do {
                let res = try JSONDecoder().decode(JSONDecoding.GetGroupsApi.self, from: result!)
                self.presenter?.scheduleByGroupsFetched(data: res)
            } catch {
                print(error)
            }
        }
    }
    func fetchStudentSchedule(week: String, cache: JSONDecoding.StudentScheduleApi?) {
        let groupId = UserDefaults.standard.integer(forKey: "user_group_id")
        let params: Parameters = [
            "app_key": Constants.AppKey,
            "type": "group",
            "id": groupId,
            "week": week
        ]
        Alamofire.request(Constants.ScheduleURL, method: .get, parameters: params).responseJSON { (response) in
            let result = response.data
            do {
                let res = try JSONDecoder().decode(JSONDecoding.StudentScheduleApi.self, from: result!)
                if let safeCache = cache {
                    if safeCache != res {
                        print("cache is deprecated")
                        clearCache(forKey: "schedule")
                        updateCache(with: result!, forKey: "schedule")
                        self.presenter?.studentScheduleFetched(data: res)
                    } else {
                        print("found in cache")
                    }
                } else {
                    print("cache is empty")
                    updateCache(with: result!, forKey: "schedule")
                    self.presenter?.studentScheduleFetched(data: res)
                }
            } catch {
                print(error)
            }
        }
    }
}
