//
//  ProfileViewController.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileViewController: UIViewController, ProfileViewProtocol {
    

	var presenter: ProfilePresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor.white
        edgesForExtendedLayout = UIRectEdge()
        let settingButton = UIButton(frame: CGRect(x: 0, y: 0, width: 30, height: 30))
        settingButton.setImage(UIImage(named: "settings"), for: .normal)
        settingButton.addTarget(self, action: #selector(setNeedsShowSettings), for: .touchUpInside)
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(customView: settingButton)
//        fillView(firstname: "", lastname: "", middlename: "", email: "", phone: "", birthday: "", nationality: "", school: "", segrys: "", photo: UIImage(named: "test")!)
        presenter?.updateView()
    }
    func fillView(data: JSONDecoding.ProfileApi) {
        let width = view.bounds.width
        DispatchQueue.global(qos: DispatchQoS.QoSClass.userInitiated).async {
            let profileLayout = ProfileLayout(data: data)
            let arrangement = profileLayout.arrangement(width: width)
            DispatchQueue.main.async(execute: {
                arrangement.makeViews(in: self.view)
            })
        }
    }
    func show(vc: UIViewController) {
        navigationController?.show(vc, sender: self)
    }
    @objc func setNeedsShowSettings() {
        presenter?.showSettings()
    }
    @objc func setNeedsShowParents() {
        presenter?.showParents()
    }
}
