//
//  ProfilePresenter.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfilePresenter: ProfilePresenterProtocol {
    weak private var view: ProfileViewProtocol?
    var interactor: ProfileInteractorProtocol?
    private let router: ProfileWireframeProtocol

    init(interface: ProfileViewProtocol, interactor: ProfileInteractorProtocol?, router: ProfileWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    func updateView() {
        interactor?.fetchProfile()
    }
    func profileFetched(firstname: String, lastname: String, middlename: String, email: String, phone: String, birthday: String, nationality: String, school: String, segrys: String, photo: UIImage) {
        view?.fillView(firstname: firstname, lastname: lastname, middlename: middlename, email: email, phone: phone, birthday: birthday, nationality: nationality, school: school, segrys: segrys, photo: photo)
    }
    func showParents() {
        view?.show(vc: ParentsRouter.createModule())
    }
    func showSettings() {
        view?.show(vc: SettingsRouter.createModule())
    }

}
