//
//  ProfileViewController.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 06/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileViewController: UIViewController, ProfileViewProtocol {

	var presenter: ProfilePresenterProtocol?

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = UIColor.white
        edgesForExtendedLayout = UIRectEdge()
        let width = view.bounds.width
        DispatchQueue.global(qos: DispatchQoS.QoSClass.userInitiated).async {
            let profileLayout = ProfileLayout(firstname: "Николай", lastname: "Борисов", middlename: "Викторович", email: "copr@vk.com", phone: "8-800-555-35-35", birthday: "01.01.2001", nationality: "RU", school: "9 Классов", segrys: "Обучался(лась) в сегрисе", photo: UIImage(named: "test")!)
            let arrangement = profileLayout.arrangement(width: width)
            DispatchQueue.main.async(execute: {
                arrangement.makeViews(in: self.view)
            })
        }
        let settingButton = UIButton(frame: CGRect(x: 0, y: 0, width: 30, height: 30))
        settingButton.setTitle("=", for: .normal)
        settingButton.addTarget(self, action: #selector(setNeedsShowSettings), for: .touchUpInside)
        self.navigationItem.rightBarButtonItem = UIBarButtonItem(customView: settingButton)
    }
    func show(vc: UIViewController) {
        navigationController?.show(vc, sender: self)
    }
    @objc func setNeedsShowSettings() {
        presenter?.showSettings()
    }
    @objc func setNeedsShowParents() {
        presenter?.showParents()
    }
}
