//
//  SettingsInteractor.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 26/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SettingsInteractor: SettingsInteractorProtocol {

    weak var presenter: SettingsPresenterProtocol?
}
