//
//  ScheduleListProtocols.swift
//  FSPO
//
//  Created Николай Борисов on 09/08/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

// MARK: Wireframe -
protocol ScheduleListWireframeProtocol: class {

}
// MARK: Presenter -
protocol ScheduleListPresenterProtocol: class {
    func updateView()
    func scheduleFetched(data: JSONDecoding.StudentScheduleApi, type: String)
    func updateSchedule(week: String)
}

// MARK: Interactor -
protocol ScheduleListInteractorProtocol: class {
    func fetchSchedule(week: String)
  var presenter: ScheduleListPresenterProtocol? { get set }
}

// MARK: View -
protocol ScheduleListViewProtocol: class {
    func showNewScheduleRows(source: JSONDecoding.StudentScheduleApi, type: String)
  var presenter: ScheduleListPresenterProtocol? { get set }
}
