//
//  JournalByTeacherInteractor.swift
//  FSPO
//
//  Created Николай Борисов on 07/08/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class JournalByTeacherInteractor: JournalByTeacherInteractorProtocol {

    weak var presenter: JournalByTeacherPresenterProtocol?
}
