//
//  JournalByTeacherProtocols.swift
//  FSPO
//
//  Created Николай Борисов on 07/08/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol JournalByTeacherWireframeProtocol: class {

}
// MARK: Presenter -
protocol JournalByTeacherPresenterProtocol: class {

}

// MARK: Interactor -
protocol JournalByTeacherInteractorProtocol: class {

  var presenter: JournalByTeacherPresenterProtocol? { get set }
}

// MARK: View -
protocol JournalByTeacherViewProtocol: class {

  var presenter: JournalByTeacherPresenterProtocol? { get set }
}
