//
//  JournalByTeacherViewController.swift
//  FSPO
//
//  Created Николай Борисов on 07/08/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import LayoutKit

class JournalByTeacherViewController: UIViewController, JournalByTeacherViewProtocol {

	var presenter: JournalByTeacherPresenterProtocol?
    private var tableView: UITableView!
    private var reloadableViewLayoutAdapter: ReloadableViewLayoutAdapter!
	override func viewDidLoad() {
        super.viewDidLoad()
        tableView = UITableView(frame: view.bounds, style: .plain)
        tableView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        reloadableViewLayoutAdapter = JournalByDateReloadableLayoutAdapter(reloadableView: tableView)
        tableView.dataSource = reloadableViewLayoutAdapter
        tableView.delegate = reloadableViewLayoutAdapter
        tableView.backgroundColor = .white
        let width = view.bounds.width
        tableView.tableHeaderView = UIView(frame: CGRect(x: 0, y: 0, width: view.bounds.width, height: 229))
        DispatchQueue.global(qos: DispatchQoS.QoSClass.userInitiated).async {
            let journalByTeacher = JournalByTeacherHeaderLayout(firstname: "a", lastname: "a", middlename: "a", email: "a", phone: "a", photo: "https://ifspo.ifmo.ru/img/users/d4b9227f0383497234869f5681263b11.jpg")
            let arrangement = journalByTeacher.arrangement(width: width)
            DispatchQueue.main.async(execute: {
                arrangement.makeViews(in: self.tableView.tableHeaderView)
            })
        }
        view.addSubview(tableView)
        reloadTableView(width: view.bounds.width, synchronous: false)
    }
    func getNewsRows() -> [Layout] {
        let shit = JSONDecoding.JournalByDateAPI.Exercises.init(ex_period: "s", ex_topic: "s", ex_type: "s", lesson_name: "s", student_presence: true, student_mark: 5, lesson_id: "s", student_performance: "s", student_dropout: false, student_delay: "false")
        let layouts = [Layout](repeating: JournalByDateCellLayout(data: shit), count: 100)
        return layouts
    }
    func getHeader(lesson: String) -> Layout {
        let layouts = HeaderLayout(text: "FIasd")
        return layouts
    }
    private func reloadTableView(width: CGFloat, synchronous: Bool) {
        var dataSource = [Section<[Layout]>]()
        for _ in self.getNewsRows() {
            dataSource.append(Section(
                header: getHeader(lesson: "item.lesson_name"),
                items: self.getNewsRows(),
                footer: nil))
        }
        reloadableViewLayoutAdapter.reloading(width: width, synchronous: synchronous, layoutProvider: { () in
            return dataSource
        })
    }

}
