//
//  DialogViewController.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 05/08/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import LayoutKit

class DialogViewController: UIViewController, DialogViewProtocol {

	var presenter: DialogPresenterProtocol?
    private var reloadableViewLayoutAdapter: ReloadableViewLayoutAdapter!
    private var tableView: UITableView!
	override func viewDidLoad() {
        super.viewDidLoad()
        tableView = UITableView(frame: view.bounds, style: .plain)
        tableView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        reloadableViewLayoutAdapter = DialogsReloadableViewLayoutAdapter(reloadableView: tableView)
        tableView.dataSource = reloadableViewLayoutAdapter
        tableView.delegate = reloadableViewLayoutAdapter
        tableView.separatorColor = .clear
        tableView.backgroundColor = UIColor.backgroundGray
        view.addSubview(tableView)
        self.reloadTableView(width: view.bounds.width, synchronous: false)
    }
    func getNewsRows() -> [Layout] {
        var layouts = [Layout]()
        /*layouts = [Layout](repeating: DialogsLayout(text: "ЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬ", isMe: true), count: 100)
        layouts.append(DialogsLayout(text: "Hello, World!", isMe: true))
        layouts.append(DialogsLayout(text: "Hello, World!", isMe: false))
        layouts.append(DialogsLayout(text: "ЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬ", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSUM(1)LOREMIPSUM(2)LOREMIPSUM(3)LOREMIPSUM(4)LOREMIPSUM(5)LOREMIPSUM(6)LOREMIPSUM(7)LOREMIPSUM(8)LOREMIPSUM(9)LOREMIPSUM(10)LOREMIPSUM(11)LOREMIPSUM(12)LOREMIPSUM(13)LOREMIPSUM(14)LOREMIPSUM(15)LOREMIPSUM(16)LOREMIPSUM(17)LOREMIPSUM(18)LOREMIPSUM(19)LOREMIPSUM(20)", isMe: true))
        layouts.append(DialogsLayout(text: "ЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬ", isMe: true))
        layouts.append(DialogsLayout(text: "ЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬЧУВЫ РЛА1РЫЩ ШВГАРФИ ЛЫНВАМФИЩЫВГЛАНФДМБ ЫИВАФДГЫЛВАР ФОИЫЛДВГАПФЫИВГНАФРЛОБВРА ИЬФДЛОТЬ", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSUM(1)LOREMIPSUM(2)LOREMIPSUM(3)LOREMIPSUM(4)LOREMIPSUM(5)LOREMIPSUM(6)LOREMIPSUM(7)LOREMIPSUM(8)LOREMIPSUM(9)LOREMIPSUM(10)LOREMIPSUM(11)LOREMIPSUM(12)LOREMIPSUM(13)LOREMIPSUM(14)LOREMIPSUM(15)LOREMIPSUM(16)LOREMIPSUM(17)LOREMIPSUM(18)LOREMIPSUM(19)LOREMIPSUM(20)", isMe: true))
        layouts.append(DialogsLayout(text: "l", isMe: true))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPS", isMe: true))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSu", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuu", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuuu", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSu", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuu", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuuu", isMe: false))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSu", isMe: true))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuu", isMe: true))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuuu", isMe: true))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuuuu", isMe: true))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuuuuu", isMe: true))
        layouts.append(DialogsLayout(text: "LOREMIPSUM(0)LOREMIPSuuuuuu", isMe: true))*/
        var cache = ""
        for i in 0...1000 {
            cache += "i"
            if i % 2 == 0 {
                layouts.append(DialogsLayout(text: cache, isMe: false))
            } else {
                layouts.append(DialogsLayout(text: cache, isMe: true))
            }
        }
        return layouts
    }
    private func reloadTableView(width: CGFloat, synchronous: Bool) {
        reloadableViewLayoutAdapter.reloading(width: width, synchronous: synchronous, layoutProvider: { [weak self] in
            return [Section(header: nil, items: self?.getNewsRows() ?? [], footer: nil)]
        })
    }
}
