//
//  DialogInteractor.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 05/08/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DialogInteractor: DialogInteractorProtocol {

    weak var presenter: DialogPresenterProtocol?
}
