//
//  ParentsProtocols.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 27/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol ParentsWireframeProtocol: class {

}
// MARK: Presenter -
protocol ParentsPresenterProtocol: class {

}

// MARK: Interactor -
protocol ParentsInteractorProtocol: class {

  var presenter: ParentsPresenterProtocol? { get set }
}

// MARK: View -
protocol ParentsViewProtocol: class {

  var presenter: ParentsPresenterProtocol? { get set }
}
