//
//  MoreViewController.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 27/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoreViewController: UIViewController, MoreViewProtocol {

	var presenter: MorePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
