//
//  LoginInteractor.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 08/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Alamofire
class LoginInteractor: LoginInteractorProtocol {

    weak var presenter: LoginPresenterProtocol?
    private var token: String?
    private var userId: Int?
    func getGroupId(user_id: Int, token: String, completion: @escaping (Bool) -> Void) {
        let parameters: Parameters = [
            "user_id": user_id
        ]
        let headers: HTTPHeaders = [
            "token": token
        ]
        Alamofire.request(Constants.StudentHistoryURL, method: .get, parameters: parameters, headers: headers).responseJSON { (response) in
            let result = response.data
            do {
                let res = try JSONDecoder().decode(JSONDecoding.StudentHistoryApi.self, from: result!)
                UserDefaults.standard.set(res.groups[res.groups.count-1].group_id, forKey: "user_group_id")
            } catch {
                print(error)
            }
            completion(true)
        }
    }
    func getToken(completion: @escaping (Bool) -> Void) {
        let params: Parameters = [
            "login": LoginLayout.loginTextField.text!,
            "password": LoginLayout.passwordTextField.text!,
            "app_key": Constants.AppKey
        ]
        Alamofire.request(Constants.AuthURL, method: .post, parameters: params).responseJSON { (response) in
            let result = response.data
            do {
                let res = try JSONDecoder().decode(JSONDecoding.AuthApi.self, from: result!)
                keychain["token"] = res.token
                UserDefaults.standard.set(res.user_id, forKey: "user_id")
                self.userId = res.user_id
                self.token = res.token
            } catch Swift.DecodingError.keyNotFound {
                do {
                    let res = try JSONDecoder().decode(JSONDecoding.ApiError.self, from: result!)
                    if res.error_code == 6 {
                        showMessage(message: NSLocalizedString("Неправильные данные!", comment: ""), y: 8)
                    } else {
                        showMessage(message: "\(NSLocalizedString("Ошибка", comment: "")): \(res.error_code)", y: 8)
                    }
                } catch {
                    print(error)
                }
            } catch {
                print("другая ошибка")
            }
            completion(true)
        }
    }
    func login() {
        let group = DispatchGroup()
        group.enter()
        getToken { _ in
            self.getGroupId(user_id: self.userId!, token: self.token!) { _ in
                group.leave()
            }
        }
        group.notify(queue: .main) {
//            print(UserDefaults.standard.string(forKey: "user_group_id"))
            self.presenter?.userLoggedIn()
        }
    }
}
