//
//  JournalByDateViewController.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 27/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import LayoutKit
class JournalByDateViewController: UIViewController, JournalByDateViewProtocol {

	var presenter: JournalByDatePresenterProtocol?
    private var tableView: UITableView!
    private var reloadableViewLayoutAdapter: ReloadableViewLayoutAdapter!
	override func viewDidLoad() {
        super.viewDidLoad()
        let width = view.bounds.width
        DispatchQueue.global(qos: DispatchQoS.QoSClass.userInitiated).async {
            let journalLayout = JournalByDateLayout()
            let arrangement = journalLayout.arrangement(width: width)
            DispatchQueue.main.async(execute: {
                arrangement.makeViews(in: self.view)
            })
        }
        let scheduleView = UIView(frame: CGRect(x: 0, y: 100, width: view.bounds.width, height: Constants.safeHeight-100))
        scheduleView.backgroundColor = .white
        view.addSubview(scheduleView)
        tableView = UITableView(frame: scheduleView.bounds, style: .plain)
        tableView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        reloadableViewLayoutAdapter = NewsReloadableViewLayoutAdapter(reloadableView: tableView)
        tableView.dataSource = reloadableViewLayoutAdapter
        tableView.delegate = reloadableViewLayoutAdapter
        tableView.backgroundColor = UIColor.backgroundGray
        scheduleView.addSubview(tableView)
    }

}
