//
//  JournalByDateProtocols.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 27/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

// MARK: Wireframe -
protocol JournalByDateWireframeProtocol: class {

}
// MARK: Presenter -
protocol JournalByDatePresenterProtocol: class {
    func updateView(date: String)
    func journalByDateFetched(data: JSONDecoding.JournalByDateAPI)
    func journalByDateShowNoLessons()
}

// MARK: Interactor -
protocol JournalByDateInteractorProtocol: class {
    func fetchJournalByDate(date: String)
    var presenter: JournalByDatePresenterProtocol? { get set }
}

// MARK: View -
protocol JournalByDateViewProtocol: class {
    func updateTableView(source: JSONDecoding.JournalByDateAPI)
    func showNoLessons()
    var presenter: JournalByDatePresenterProtocol? { get set }
}
