//
//  JournalByDateViewController.swift
//  FSPO-Viper
//
//  Created Николай Борисов on 27/07/2018.
//  Copyright © 2018 Николай Борисов. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class JournalByDateViewController: UIViewController, JournalByDateViewProtocol {

	var presenter: JournalByDatePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        let width = view.bounds.width
        DispatchQueue.global(qos: DispatchQoS.QoSClass.userInitiated).async {
            let journalLayout = JournalByDateLayout()
            let arrangement = journalLayout.arrangement(width: width)
            DispatchQueue.main.async(execute: {
                arrangement.makeViews(in: self.view)
            })
        }
    }

}
